language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
matrix:
  allow_failures:
    - go: tip

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
      secure: "FM/6haW5DUjQD1IpPH3glFk075cnS0foazoiPHCHV+Rk1+WgMoxh4cIbXJnOnYLOUlt9l+8NyqG4P48Ia7Kn1RpqAWKbcPHCB4R1v7dug8tZCv2lt7YOenfmykXSbkK6d4uqIPredQK4MT6jhog0CG05bOhkOinxiZbM2wCftbM="
    on_failure: always
    on_success: always
env:
  global:
  - secure: RlcL7can+9hEODLqSO2hFgCJbmDgj8w8Jjrxl8qDYUxseglz/7rvjW8olWXLnTQXZI1i2j1Nl6jkLvjkveDJSxgA76DkK6wf0JzdcPgL4sSuEfCk7MK8WxG+CdNOgK9yeYkGq5GVNW01DBHy7/ecFm5avjKI/z5QBnAhxqvV6gc=
  - secure: WPhffcHui8ai8eCuR/J2eVnKK2zHnAv3ToVWRaAfW6FuF3L9/fe9ZxDLJtw+1un3I7WXgJaiRvXq+3S1KcWw6nJOgpi9AOp2So6PWDmSTVsVDyksRXOes4pMIhtB80918flm5C0puld88Hlqllfu4sm88eiAGuFDM4H9pmVw8xE=
