language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
matrix:
  allow_failures:
    - go: tip

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
      secure: "FM/6haW5DUjQD1IpPH3glFk075cnS0foazoiPHCHV+Rk1+WgMoxh4cIbXJnOnYLOUlt9l+8NyqG4P48Ia7Kn1RpqAWKbcPHCB4R1v7dug8tZCv2lt7YOenfmykXSbkK6d4uqIPredQK4MT6jhog0CG05bOhkOinxiZbM2wCftbM="
    on_failure: always
    on_success: always
env:
  global:
  - secure: fTokWlm4a9RFZ2B6qIKLl9rw2CVcG9tVNnifHRmvlPMTalgJ4MpZkBhgoHokC+pIhlC47Nd2YKJ44cv5xwL7oie+yDBdat+ceuQ0XaF1bENtDGfs8t8IGLq4kEZ5M6lBuAr2b+v+WfGR11iGeFzGuuLf9m2C9idVXVOiHEvy+KM=
  - secure: M9NKzWz3gkWU5aXAxdm2GtpLLy/1Nswh0tYoCY0cHoM/005T+zsd84cK47rJl8I2qopJ5/sh5R91wS1MkR0ghdBfRhu9n652e4YdC5k+lkI3icu2n4YA6D2UXRO77e7hie2OSTcG0XY17LNYp59f2d1id5kGJuBIf/dWyLk+FLU=