language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
matrix:
  allow_failures:
    - go: tip

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
      secure: "ZD1CNctKh8bFaeXVrTYaPeEkupKkPe9pQ0SOdGIC5qOBVK95WHiQr/C+3QIs6YCY/IBU0HFhV04jv8MzWl69u5aoIxO+KxF6VY+k1MwdsSzmmea7DcUbq3h/NFVh8llZJ0UKi+24z0OvZuqZ/xaRaWI3KBZ5XAGxckaD1yqJ0xU="
    on_failure: always
    on_success: always
env:
  global:
  - secure: fTokWlm4a9RFZ2B6qIKLl9rw2CVcG9tVNnifHRmvlPMTalgJ4MpZkBhgoHokC+pIhlC47Nd2YKJ44cv5xwL7oie+yDBdat+ceuQ0XaF1bENtDGfs8t8IGLq4kEZ5M6lBuAr2b+v+WfGR11iGeFzGuuLf9m2C9idVXVOiHEvy+KM=
  - secure: M9NKzWz3gkWU5aXAxdm2GtpLLy/1Nswh0tYoCY0cHoM/005T+zsd84cK47rJl8I2qopJ5/sh5R91wS1MkR0ghdBfRhu9n652e4YdC5k+lkI3icu2n4YA6D2UXRO77e7hie2OSTcG0XY17LNYp59f2d1id5kGJuBIf/dWyLk+FLU=
