language: go
go:
- 1.1
- 1.2
- 1.3
- tip
matrix:
  allow_failures:
    - go: tip

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
      secure: "ZD1CNctKh8bFaeXVrTYaPeEkupKkPe9pQ0SOdGIC5qOBVK95WHiQr/C+3QIs6YCY/IBU0HFhV04jv8MzWl69u5aoIxO+KxF6VY+k1MwdsSzmmea7DcUbq3h/NFVh8llZJ0UKi+24z0OvZuqZ/xaRaWI3KBZ5XAGxckaD1yqJ0xU="
    on_failure: always
    on_success: always
env:
  global:
  - secure: gyhp4hcFDjTlPw2sFv7lK8szAMklF7YE1MOZBuwIfQJBiT2VlQ1IpQe+oC+lcEMdoL9ZomD1BfBQaA1s0QLXkcbHEaB/LCWn5/vLheJgqANJwO4Wllymzcws4+hC0s2xx0E16K8eLkmxA7s+ybwfjZdT+5ZbVc8/wTT/yC5Yfew=
  - secure: jGgQwD5gfeVx6o4k7SJMGJZNkN7KMvYlnclBhzNdEJUtk433T4FfKCt23A/sfCuqtX49EulryKufYwe3gbWpan2nXJny8QdJq7YizdZ5qULcYm0cMqg4u5kuQ2nUwEj94dpWwEn7isLck38+j4jWCtKmeNa3rJfKG4J4r9tjaXA=
