language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
matrix:
  allow_failures:
    - go: tip

# travis encrypt [subdomain]:[api token]@[room id]
notifications:
  email: false
  campfire:
    rooms:
      secure: "CnAd9SmsrogIQ7CKL0nAun6qgJS7TGdB/GcVz1r9bThszpe9HdAkVsNn699St9MUBAWPMetZnm/j2yJ7WJCR3e8oDygDmJcd6Rekg5UwwdL7esbcguCDMiD9XNuFldr2ZS+htVF8NSYognn/9wgki6LDNKM/pY+uYZce83Y2aMs="
    on_failure: always
    on_success: always
env:
  global:
  - secure: RlcL7can+9hEODLqSO2hFgCJbmDgj8w8Jjrxl8qDYUxseglz/7rvjW8olWXLnTQXZI1i2j1Nl6jkLvjkveDJSxgA76DkK6wf0JzdcPgL4sSuEfCk7MK8WxG+CdNOgK9yeYkGq5GVNW01DBHy7/ecFm5avjKI/z5QBnAhxqvV6gc=
  - secure: WPhffcHui8ai8eCuR/J2eVnKK2zHnAv3ToVWRaAfW6FuF3L9/fe9ZxDLJtw+1un3I7WXgJaiRvXq+3S1KcWw6nJOgpi9AOp2So6PWDmSTVsVDyksRXOes4pMIhtB80918flm5C0puld88Hlqllfu4sm88eiAGuFDM4H9pmVw8xE=
